<?php

/**
 * @file
 * Primary module hooks for Bootstrap Toolbox List_Group module.
 */


use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;


use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Template\Attribute;


use Drupal\views\Plugin\views\style\StylePluginBase; 

use Drupal\views\ViewExecutable;
use Drupal\Component\Utility\NestedArray;

use Drupal\Core\Link;
use Drupal\Core\Render\Markup;


include_once __DIR__ .'/includes/bt_list_group_field_formatter_alter.inc' ;
include_once __DIR__ .'/includes/bt_list_group_panel_view_plugin.inc' ;



function template_preprocess_views_style_bt_list_group_list(&$variables){

  $utilityService = \Drupal::service('bootstrap_toolbox.utility_service');

  $view = $variables['view'];
  $options = $view->style_plugin->options;
  $options['card_style'] = $utilityService->getStyleById($options['card_style']);
  $options['header_style'] = $utilityService->getStyleById($options['header_style']);
  $options['body_style'] = $utilityService->getStyleById($options['body_style']);


  
  $variables['options'] = $options;
  $currentDisplay = $view->current_display;
  
  $displayTitle = $view->getTitle();
  if(empty($displayTitle)){
    $currentDisplay = $view->current_display;
    $displayTitle = $view->storage->getDisplay($currentDisplay)['display_title'];
  }
  $variables['title'] = $displayTitle;
  
  
  $variables['default_row_class'] = $options['default_row_class'];
  foreach ($variables['rows'] as $id => $row) {
    $variables['rows'][$id] = [
      'content' => $row,
      'attributes' => (new \Drupal\Core\Template\Attribute())->addClass(''),
    ];
    if ($row_class = $view->style_plugin->getRowClass($id)) {
      $variables['rows'][$id]['attributes']->addClass($row_class);
    }
  }
  
  
}
