views.style.bt_list_group_panels:
  type: views_style
  label: 'List Group with Panels'
  mapping:
    wrapper_class:
      type: string
      label: 'Wrapper class'


views.display_extender.bt_list_group:
  type: mapping
  label: 'Views Attach Library Settings'
  mapping:
    attach_library:
      type: mapping
      label: 'The libraries to be attached'
      mapping:
        attach_library:
          type: string
          label: 'The libraries to be attached'


